backend:
  name: github
  repo: angelod1as/mae-urso

media_folder: static/assets
public_folder: assets

# publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: blog
    label: Posts no Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: date, label: Data de publicação, widget: date }
      - { name: title, label: Título, widget: string }
      - name: descGroup
        label: Descrições
        widget: object
        fields:
          - { name: desc, label: Descrição curta, widget: string }
          - { name: longdesc, label: Descrição sidebar, widget: text }
      # - { name: tags, label: Tags, widget: list }
      - { name: thumbnail, label: Imagem do post, widget: image }
      - { name: body, label: Texto, widget: markdown }
      - name: others
        label: Outras
        widget: object
        fields:
          - { name: hide, label: Esconder da home, widget: boolean, default: false, required: false }

  - name: home
    label: Itens da Home
    folder: content/home
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Título, widget: string }
      - { name: background, label: Imagem de fundo, widget: image, required: false }
      - { name: body, label: Texto, widget: markdown, required: false }
      - { name: order, label: Ordem, widget: number }

  - name: pages
    label: Páginas
    folder: content
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Título, widget: string }
      - { name: body, label: Texto, widget: markdown }
      - { name: form, label: Nome do formulário, widget: string, required: false }

  - name: cardapios
    label: Cardápios
    folder: content/cardapios
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: date, label: Data de publicação, widget: date }
      - { name: title, label: Título, widget: string }
      - name: descGroup
        label: Descrições
        widget: object
        fields:
          - { name: desc, label: Descrição curta, widget: string }
          - { name: longdesc, label: Descrição sidebar, widget: text }
      # - { name: tags, label: Tags, widget: list }
      - { name: thumbnail, label: Imagem do post, widget: image }
      - { name: body, label: Texto, widget: markdown }
      - { name: include, label: O que o menu inclui, widget: list }